---

name: build

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# secrets:
#   DOCKERHUB_TOKEN:
#     required: false

env:
  IMAGE_NAME: publicface.github.io
  IMAGE_REPOSITORY_USER: powareverb
  DOCKERHUB_USERNAME: powareverb

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Needed for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx with docker driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          #context: ${{ inputs.folder }}
          load: true
          sbom: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Export image artifact
        run: |
          docker image save ${{ env.IMAGE_REPOSITORY_USER }}/${{ env.IMAGE_NAME }}:{{ github.sha }} | gzip > ${{ env.IMAGE_NAME }}-${{ github.sha }}.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ github.sha }}
          path: ${{ env.IMAGE_NAME }}-${{ github.sha }}.tar.gz
          retention-days: 1

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx with docker-container driver
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v5
        with:
          # context: ${{ inputs.folder }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          push: true
          sbom: true
          cache-from: type=gha
          cache-to: type=gha
